# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  realestateapi:
    image: realestateapi
    build:
      context: .
      dockerfile: RealEstate.Api/Dockerfile
    ports:
      - 5000:5000
